### ISSUE TITLE
Possible false negative ?

### ISSUE THREAD

**Issue by terotests** [vkomulai/finnish-bank-utils#15]
Some IBAN calculators / generators give "FI3369403290724924" as valid FI IBAN, but this seemed to not pass `FinnishBankUtils.isValidFinnishIBAN`

```javascript
const FinnishBankUtils = require("finnish-bank-utils")
console.log(FinnishBankUtils.isValidFinnishIBAN("FI3369403290724924"))
```
I'm not 100% certain if that number is really a valid number, but it seems to pass 
https://bank.codes/iban/validate/
However, this site gives:
https://www.ibancalculator.com/iban_validieren.html
https://www.iban.com/
"The checksum in the account number is incorrect."

However, Nordea thinks it is fine:
https://www.nordea.com/fi/palvelut/cashmanagement/iban-validator-and-information/iban-validator/

Not sure which site is correct.

**Comment by vkomulai** [comment]
I checked using this site as well: https://www.iban.com/

It says, that "Account Number checksum is invalid." and "IBAN Checksum is valid"

So I think that Nordea checker doesn't check the validity of the Finnish account number scheme, it only checks for valid IBAN scheme, those are two different things / validations.

**Comment by terotests** [comment]
Yes, you are right. I encountered this problem actually when I used IBAN number generator, which did not generate valid Finnish Account numbers. So it was just for testing purposes.

The Solution: I should have used `FinnishBankUtils.generateFinnishRefIBAN()`
